[package]
name = "talk-rust-const-fn"
version = "0.1.0"
authors = ["mgr-inz-rafal <rchabowski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm_cursor = "0.2.6"
crossterm_terminal = "0.2.6"